services:
  seed:
    build: .
    container_name: seed
    environment:
      NODE_ADDR: "seed:8080"
      SEED_ADDR: "seed:8080"
      IS_SEED: "true"
    networks:
      - cluster_net

  node:
    build: .
    environment:
      # Usa lâ€™hostname come indirizzo:
      NODE_ADDR: "${HOSTNAME}:8080"
      SEED_ADDR: "seed:8080"
      IS_SEED: "false"
    depends_on:
      - seed
    networks:
      - cluster_net

networks:
  cluster_net:

