services:
  seed:
    build: .
    container_name: seed
    environment:
      -host: "127.0.0.1"
      -port: "6767"
      -seed: "true"
    networks:
      - cluster_net

  node:
    build: .
    environment:
      -host: "127.0.0.1"
      -port: "8080"
      -seed: "false"
    depends_on:
      - seed
    networks:
      - cluster_net

networks:
  cluster_net:
